### Send POST request with json body
POST http://localhost:8080//auth/register
Content-Type: application/json

{
  "username": "zderival1",
  "email": "zderival1@gmail.com",
  "password": "Godisgood10."
}

###

POST http://localhost:8080//auth/login
Content-Type: application/json

{
  "username": "zderival1",
  "password": "Godisgood10."
}

> {%
    client.global.set("token", response.body.token);
 %}

###

POST http://localhost:8080/recipes/search
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ingredients": ["zzz", "fakefood", "xyz123"],
  "cuisine": "",
  "diet": "",
  "allergies": [],
  "preferences": []
}

###

POST http://localhost:8080/saved/save
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "spoonacularId": 716361
}

###
GET http://localhost:8080/saved/getRecipes
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

###

DELETE http://localhost:8080/saved/remove
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "spoonacularId": 716361
}

###
POST http://localhost:8080/profile/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "diet": "vegetarian",
  "goal": "lose weight",
  "allergies": ["peanuts", "shellfish"],
  "preferences": ["high protein", "low carb"]
}

###
GET http://localhost:8080/profile/get
Content-Type: application/json
Authorization: Bearer {{token}}

{
}

###
PUT http://localhost:8080/profile/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "goal": "build muscle"
}

###
DELETE http://localhost:8080/profile/delete
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

###
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
Content-Type: application/json
x-goog-api-key: {{$env.gemini_api_key}}

{
  "contents": [
    {
      "parts": [
        { "text": "Say hello in one sentence." }
      ]
    }
  ]
}

###
GET http://localhost:8080/recommendations/getRecommendations
Content-Type: application/json
Authorization: Bearer {{token}}

{

}