### Send POST request with json body
POST http://localhost:8080//auth/register
Content-Type: application/json

{
  "username": "zderival1",
  "email": "zderival1@gmail.com",
  "password": "Godisgood10."
}

###

POST http://localhost:8080//auth/login
Content-Type: application/json

{
  "username": "zderival",
  "password": "Godisgood1"
}

###

POST http://localhost:8080/recipes/search
Content-Type: application/json

{
  "ingredients": ["chicken", "rice", "garlic"],
  "cuisine": "",
  "diet": "",
  "allergies": [],
  "preferences": []
}