spring.application.name=FoodMaster

spring.datasource.url=jdbc:mysql://localhost:3306/food_master
spring.datasource.username=${MYSQL_Username}
spring.datasource.password=${MYSQL_Password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${jwt_key}
jwt.expiration=86400000

spoonacular.api.key=${spoonacualr_api_key}
logging.level.org.springframework.web=DEBUG
spring.main.allow-circular-references=true

gemini.api.key=${gemini_api_key}